# Generated by Django 4.1.7 on 2023-03-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя и фамилия врача')),
                ('picture', models.FileField(upload_to='doctors_pictures/%Y/%m/%d')),
                ('speciality', models.CharField(max_length=300, verbose_name='Специализация')),
                ('experience', models.CharField(max_length=100, verbose_name='Стаж работы')),
                ('education', models.TextField(verbose_name='Образование')),
                ('additional_qualification', models.TextField(blank=True, verbose_name='Повышение квалификации')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название процедуры')),
                ('price', models.IntegerField(verbose_name='Цена, руб.')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('doctor_mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', to_field='name')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(to='main.service'),
        ),
    ]
