# Generated by Django 4.1.7 on 2023-03-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка на источник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя, фамилия и отчество врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.FileField(upload_to='doctors_pictures/%Y/%m/%d', verbose_name='Фото врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(to='main.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor_mentioned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', to_field='name', verbose_name='Доктор, о котором идёт речь'),
        ),
    ]
