# Generated by Django 4.1.7 on 2023-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_source_alter_doctor_name_alter_doctor_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor_mentioned',
        ),
        migrations.AddField(
            model_name='review',
            name='doctors_mentioned',
            field=models.ManyToManyField(to='main.doctor', verbose_name='Доктора, о которых идёт речь'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Фамилия, имя и отчество врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Ссылка, которая будет вести к врачу. Это поле заполняется само, не нужно его трогать. Вписав сюда что-то, вы ничего не испортите, но и лучше от этого не станет.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Ссылка, которая будет вести к услуге. Это поле заполняется само, не нужно его трогать. Вписав сюда что-то, вы ничего не испортите, но и лучше от этого не станет.'),
        ),
    ]
