# Generated by Django 4.1.7 on 2023-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_review_doctor_mentioned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='carousel_pictures', verbose_name='Изображение')),
                ('description', models.CharField(max_length=150, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Изображение для слайд-шоу',
                'verbose_name_plural': 'Изображения для слайд-шоу',
            },
        ),
    ]
