# Generated by Django 4.1.7 on 2023-03-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carouselpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
