# Generated by Django 4.1.7 on 2023-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('wishes', models.CharField(max_length=150, verbose_name='Пожелания')),
            ],
            options={
                'verbose_name': 'Запрос звонка',
                'verbose_name_plural': 'Запросы звонков',
            },
        ),
    ]
