# Generated by Django 4.1.7 on 2023-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Стоматология', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='wishes',
            field=models.CharField(max_length=2000, verbose_name='Пожелания'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.service', verbose_name='Услуги'),
        ),
    ]
