# Generated by Django 4.1.7 on 2023-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_category_alter_callrequest_wishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='biomaterial',
            field=models.CharField(max_length=2000, null=True, verbose_name='Биоматериал'),
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(max_length=2000, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(max_length=2000, null=True, verbose_name='Срок выполнения (рабочие дни) (день забора не учитывается)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Название процедуры'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=2000, null=True, verbose_name='Цена, руб.'),
        ),
    ]
