# Generated by Django 4.1.7 on 2023-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_service_category_service_biomaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=3000, null=True, verbose_name='Название процедуры'),
        ),
    ]
