# Generated by Django 4.1.7 on 2023-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Анализы', max_length=1000, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
