# Generated by Django 4.1.7 on 2023-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory_slug',
            field=models.CharField(max_length=2000, null=True, verbose_name='Слаг подкатегории'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.CharField(max_length=2000, null=True, verbose_name='Подкатегория'),
        ),
    ]
