# Generated by Django 4.1.7 on 2023-06-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service_subcategory_slug_alter_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
