# Generated by Django 4.1.7 on 2023-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='certififcates', verbose_name='Фото/скан сертификата')),
                ('description', models.CharField(max_length=1000, verbose_name='Короткое описание (о чём сертификат?)')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
