# Generated by Django 4.1.7 on 2023-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_indexpicture_alter_certificate_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='additional_qualification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='services',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, verbose_name='(пока не используется на сайте) Образование'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='(пока не используется на сайте) Стаж работы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='(пока не используется на сайте) Ссылка, которая будет вести к врачу. Это поле заполняется само, не нужно его трогать. Вписав сюда что-то, вы ничего не испортите, но и лучше от этого не станет.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='biomaterial',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Биоматериал (только для анализов)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Подкатегория (только для анализов)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory_slug',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Слаг подкатегории (только для анализов, оставьте пустым — поле заполняется само)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Срок выполнения в рабочих днях без учёта дня забора (только для анализов)'),
        ),
    ]
