# Generated by Django 4.1.7 on 2023-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Слаг (оставьте пустым — поле заполнится само)'),
        ),
    ]
