# Generated by Django 4.1.7 on 2023-07-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_newspost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='addition_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
